server:
  port: 8081
  servlet.session:
    cookie.max-age: 0
    timeout: 0
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pcb_main?serverTimeZone=Asia/Singapore
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        jdbc:
          time_zone: Asia/Singapore
        show_sql: true
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: pcbuilder
  resource: pcbuilder-app
  public-client: true
        
logging:
  level:
    root: info
    com.polykhel.pcb: debug
    org:
      hibernate:
        type: trace